server {
    listen 80;
    server_name localhost;
    client_max_body_size 50M;

    location /api {
        try_files $uri @backend;
    }

    location /sanctum {
        try_files $uri @backend;
    }

    location /storage {
        try_files $uri @backend;
    }

    location /up {
        try_files $uri @backend;
    }

    location / {
        proxy_pass http://frontend:4200;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location @backend {
        root /var/www/html/public;
        fastcgi_pass backend:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        include fastcgi_params;
        fastcgi_param HTTP_PROXY "";
        fastcgi_param REQUEST_URI $request_uri;
    }
}
